### ISSUE TITLE
The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by farvex** [ameyer505/D365FOSecurityTestWorkspace#5]
Hi Alex,

When I run the application, nothing happens. No error or exception is displayed.
However, I have found two error messages in the Event viewer/Application section.

**Exception 1:**
Application: D365FOSecurityTestWorkspace.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at D365FOSecurityTestWorkspace.APIClient.DynamicsAx7ODataClient..ctor(D365FOSecurityTestWorkspace.Models.Ax7Credentials)
   at D365FOSecurityTestWorkspace.MainForm..ctor()
   at D365FOSecurityTestWorkspace.Program.Main()

**Exception 2:**
Faulting application name: D365FOSecurityTestWorkspace.exe, version: 1.0.0.0, time stamp: 0xed752a67
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0992e110
Faulting process id: 0xb18
Faulting application start time: 0x01d75203b34f8342
Faulting application path: D:\data\download\D365FOSecurityTestWorkspace.exe
Faulting module path: unknown
Report Id: 0a911ec5-58fd-4ae6-8910-3a02e514a5b0
Faulting package full name: 
Faulting package-relative application ID: 

Also, there were a couple of other records.
**Information 1:**
Fault bucket, type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: D365FOSecurityTestWorkspace.exe
P2: 1.0.0.0
P3: ed752a67
P4: D365FOSecurityTestWorkspace
P5: 1.0.0.0
P6: ed752a67
P7: 102
P8: 15
P9: System.NullReferenceException
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_D365FOSecurityTe_a4177e45e7e65b3360662c3c5fbf79c67c9a8bd5_3a7d37d6_7fc13791-c555-4a92-be83-9071d2b1ef40

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0a911ec5-58fd-4ae6-8910-3a02e514a5b0
Report Status: 4
Hashed bucket: 
Cab Guid: 0

**Information 2:**
Fault bucket 1277502305820280519, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: D365FOSecurityTestWorkspace.exe
P2: 1.0.0.0
P3: ed752a67
P4: D365FOSecurityTestWorkspace
P5: 1.0.0.0
P6: ed752a67
P7: 102
P8: 15
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA484.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_D365FOSecurityTe_a4177e45e7e65b3360662c3c5fbf79c67c9a8bd5_3a7d37d6_7fc13791-c555-4a92-be83-9071d2b1ef40

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0a911ec5-58fd-4ae6-8910-3a02e514a5b0
Report Status: 268435456
Hashed bucket: a48866bd74a8f83e11ba9994222906c7
Cab Guid: 0

==============================

I believe, the main issue is caused by referencing a NULL object (System.NullReferenceException).
Are there any other pre-requisites to run the app?

**Comment by ameyer505** [comment]
Please view the subsequent blog post on the solution along with prerequisite: https://alexdmeyer.com/2021/05/19/beta-release-of-d365fo-security-role-test-workspace/

Here is an excerpt of the setup process:

    Create an app registration for our external application to authenticate to your AAD -> D365FO instances
        Links to help
            https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/services-home-page
            https://d365byjp.blogspot.com/2019/12/registering-microsoft-dynamics-365.html
        Set up Azure Active Directory Applications in System Administrator -> Setup -> Azure Active Directory Applications
    Navigate to the D365FO Security Test Workspace GitHub page
        Either download the latest pre-built release or clone the entire project locally and build it yourself
    If not a current Fastpath customer, you need to download and install the deployable package into your D365FO environment
        Assign the AMSecurityRoleTest role to the service account user tied to the Azure Active Directory Applications

**Comment by farvex** [comment]
I had completed the setup process and double-checked it before creating the issue.
Today, I have re-done it again. No luck (the error is the same):
Application: D365FOSecurityTestWorkspace.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at D365FOSecurityTestWorkspace.APIClient.DynamicsAx7ODataClient..ctor(D365FOSecurityTestWorkspace.Models.Ax7Credentials)
   at D365FOSecurityTestWorkspace.MainForm..ctor()
   at D365FOSecurityTestWorkspace.Program.Main()

BTW, I am running the app outside my crop domain. But, in my understanding, if we set up a multitenant account type on Azure Portal, it should work as well. What I might have missed? I'll contact our network admins to allow me to run the EXE file within our network to be able to test it inside our domain.

**Comment by ameyer505** [comment]
I apologize I misunderstood the initial issue (that it was occurring during the launch of the application not during the actual use), I have tested a fix and have released v1.3 to address this. Please let me know if there are additional issues.

Also just as a heads up, there is no need to be on a corporate network for the application to function.

**Comment by farvex** [comment]
Hi Alex,

Thank you so much for your prompt response!
I'll let you know the results.

I'm going to test the app very intensively and I'll let you know about issues (if any).

Thanks,
Sergey

**Comment by farvex** [comment]
It works fine now.
Thanks a lot!
