### ISSUE TITLE
The list of roles is not cleaned up after selecting another user.

### ISSUE THREAD

**Issue by farvex** [ameyer505/D365FOSecurityTestWorkspace#8]
Hi Alex,

The list of roles is not cleaned up after selecting another user.
Maybe it's not an issue, but it would be good to update the list with actual roles (to avoid any unexpected testing results).

**Reproduction steps:**
1. Load security roles
2. Select user A (with Roles 1 and 2)
3. Click Load User Roles (Roles 1 and 2 appear on the list)
4. Select user B (with Role 3)
5. Click Load User Roles
- Expected result: **only Role 3 is displayed on the list**
- Actual result: **Roles 1, 2, and 3**

**Comment by ameyer505** [comment]
This is fixed in the 1.4 release
