### ISSUE TITLE
There are bad ("dead") references to the deleted role Security Role Test Workspace

### ISSUE THREAD

**Issue by farvex** [ameyer505/D365FOSecurityTestWorkspace#9]
Hi Alex,

After removing the security test role (by clicking on the **Remove Security Test Role** button), I see many bad references (on the **Security diagnostics** form) to the deleted role **Security Role Test Workspace**. Please see below:
<img width="387" alt="dead_references" src="https://user-images.githubusercontent.com/2647398/119802591-c63ba600-bf32-11eb-8b7d-2e930360af6f.png">.

I am sure all of the empty records (with no label) refer to the role **Security Role Test Workspace**.

For example, for the highlighted string (see the screenshot above), the query:
```
SELECT *
  FROM dbo.SECURITYOBJECTEVENT AS T
 WHERE T.IDENTIFIER = '{GUID}'
```
returns the following results:
```
OBJECTTYPE	IDENTIFIER	LABEL	USERID	EVENTTYPE
0	99999999-7857-483d-ab66-99d0b9b68a16	Security Role Test Workspace	AAAAAAA  4
0	99999999-7857-483d-ab66-99d0b9b68a16	Security Role Test Workspace	AAAAAAA  0
0	99999999-7857-483d-ab66-99d0b9b68a16	Security Role Test Workspace	AAAAAAA  2
0	99999999-7857-483d-ab66-99d0b9b68a16	Security Role Test Workspace	AAAAAAA  1
```

**Comment by farvex** [comment]
I have figured out that the issue might be caused by the records in the table SECURITYROLEPARENTREFERENCES. I see bad references there.
```
SELECT *
  FROM dbo.SECURITYROLEPARENTREFERENCES AS T
 WHERE T.DATA LIKE '%99999999-7857-483d-ab66-99d0b9b68a16%'
```

Result:
The role 8f715b88-fb86-41ed-8c22-3313b2cbf8f4 has the reference to the deleted **Security Role Test Workspace (99999999-7857-483d-ab66-99d0b9b68a16)**:
```
<RoleParents xmlns="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Security.Management" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
	<Name>8f715b88-fb86-41ed-8c22-3313b2cbf8f4</Name>
	<Roles xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
		<a:string>11111111-b931-497f-b59a-2066839b75cc</a:string>
		<a:string>99999999-7857-483d-ab66-99d0b9b68a16</a:string>
		<a:string>22222222-6c62-4361-845e-d1de1b423f8e</a:string>
		<a:string>33333333-ec1d-42d5-bc88-cba19b1c61a5</a:string>
		<a:string>44444444-8bf7-4f19-8049-b1a5e8812400</a:string>
		<a:string>55555555-fa59-452a-99f3-4b85458fc884</a:string>
		<a:string>66666666-6b65-4b9a-98d4-e909f122b03a</a:string>
	</Roles>
</RoleParents>
```

**Comment by farvex** [comment]
To fix all bad references, I have developed the following script:
```
DECLARE @PARENT_ROLE_ID AS NVARCHAR(100);
DECLARE @ROLE_ID        AS NVARCHAR(100);

DECLARE SEC_ROLE_OBJECT_ITERATOR CURSOR FOR
WITH XMLNAMESPACES (DEFAULT 'http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Security.Management',
                    'http://www.w3.org/2001/XMLSchema-instance'                 as i,
                    'http://schemas.microsoft.com/2003/10/Serialization/Arrays' as a)
SELECT t.IDENTIFIER                                 AS [ROLE],
       CAST(n.dap.query('text()') AS NVARCHAR(100)) AS [PARENT_ROLE]
  FROM (SELECT s.IDENTIFIER,
               CAST(s.DATA AS XML) AS [DATA]
          FROM dbo.SECURITYROLEPARENTREFERENCES AS s) AS t
 CROSS APPLY t.[DATA].nodes('/RoleParents/Roles/a:string') AS n(dap)
 ORDER BY t.IDENTIFIER;

OPEN SEC_ROLE_OBJECT_ITERATOR;
FETCH NEXT FROM SEC_ROLE_OBJECT_ITERATOR INTO @ROLE_ID, @PARENT_ROLE_ID;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS(SELECT 1
                    FROM dbo.SECURITYROLE AS t
                   WHERE UPPER(t.AOTNAME) = UPPER(@PARENT_ROLE_ID))
    BEGIN
        UPDATE t
           SET t.DATA = REPLACE(t.DATA, '<a:string>' + @PARENT_ROLE_ID + '</a:string>', '')
          FROM dbo.SECURITYROLEPARENTREFERENCES AS t
         WHERE t.IDENTIFIER = @ROLE_ID;
    END;

    FETCH NEXT FROM SEC_ROLE_OBJECT_ITERATOR INTO @ROLE_ID, @PARENT_ROLE_ID;
END;

CLOSE      SEC_ROLE_OBJECT_ITERATOR;
DEALLOCATE SEC_ROLE_OBJECT_ITERATOR;
```

After running the script, all issues have been resolved.
However, this approach won't work on PROD (because of no access to SQL).

**Comment by farvex** [comment]
The same issues found in two other tables SECURITYDUTYPARENTREFERENCES and SECURITYPRIVILEGEPARENTREFERENCES. They can be fixed with a similar script.

**Comment by ameyer505** [comment]
This issue is present without using this application as well within D365FO. For example, I created a new role within the D365FO user interface and assigned it some security. It now shows up when I go to Security Diagnostics:
![image](https://user-images.githubusercontent.com/3227457/120353764-80326980-c2c7-11eb-973a-ee96469241d5.png)

Now if I go and remove this security layer via the user interface as well and go back to the same form -> Security Diagnostics you can see the 'blank' reference is still there:
![image](https://user-images.githubusercontent.com/3227457/120353956-b07a0800-c2c7-11eb-9215-8dac44a29c6b.png)

So there is a bug within D365FO when removing a security layer that the security metadata is not removed.

I did find that if you go into the Security Configuration form and run the Data -> Repair option it seems to fix the issue:

![image](https://user-images.githubusercontent.com/3227457/120354411-0353bf80-c2c8-11eb-8ced-2f18a95c5c53.png)


![image](https://user-images.githubusercontent.com/3227457/120354273-e9b27800-c2c7-11eb-9eb2-577c6cc872a6.png)

**Comment by farvex** [comment]
Thanks Alex!
I have never used the 'Repair' button before (I just didn't know what was the purpose of it.).
So, looks like that button was built by Microsoft as a workaround/fix for the bug in D365FO.
